TAGPOWER.TAGPOWERDATA.push(

                    ["CO_BRAID",   "CO_EILI",       qsTr("True Bond"),  30,     3],

                    ["CO_DANIAL",   "CO_ADDER",     qsTr("Tagpower"),   -10,    0],
                    ["CO_DANIAL",   "CO_BEAST",     qsTr("Tagpower"),   -20,    0],
                    ["CO_DANIAL",   "CO_BRENNER",   qsTr("Tagpower"),   10,     1],
                    ["CO_DANIAL",   "CO_CAIRN",     qsTr("Tagpower"),   10,     1],
                    ["CO_DANIAL",   "CO_CASSIDY",   qsTr("Tagpower"),   -10,    0],
                    ["CO_DANIAL",   "CO_CAULDER",   qsTr("Tagpower"),   -30,    0],
                    ["CO_DANIAL",   "CO_DAVIS",     qsTr("Tagpower"),   -10,    0],
                    ["CO_DANIAL",   "CO_EVA",       qsTr("Tagpower"),   -20,    0],
                    ["CO_DANIAL",   "CO_FLAK",      qsTr("Tagpower"),   -10,    0],
                    ["CO_DANIAL",   "CO_FORSYTHE",  qsTr("Tagpower"),   10,     1],
                    ["CO_DANIAL",   "CO_GAGE",      qsTr("Tagpower"),   -5,     0],
                    ["CO_DANIAL",   "CO_GRAVES",    qsTr("Tagpower"),   -20,    0],
                    ["CO_DANIAL",   "CO_GREYFIELD", qsTr("Tagpower"),   -20,    0],
                    ["CO_DANIAL",   "CO_GRIMM",     qsTr("Tagpower"),   -10,     0],
                    ["CO_DANIAL",   "CO_GRIT",      qsTr("Half A Cause"),   20,     2],
                    ["CO_DANIAL",   "CO_HAWKE",     qsTr("Tagpower"),   -20,    0],
                    ["CO_DANIAL",   "CO_ISABELLA",  qsTr("Tagpower"),   10,     1],
                    ["CO_DANIAL",   "CO_JAVIER",    qsTr("Tagpower"),   -10,    0],
                    ["CO_DANIAL",   "CO_JOEY",      qsTr("Tagpower"),   -20,    0],
                    ["CO_DANIAL",   "CO_JULIA",     qsTr("Tagpower"),   -20,    0],
                    ["CO_DANIAL",   "CO_KANBAI",    qsTr("Tagpower"),   -10,    0],
                    ["CO_DANIAL",   "CO_KINDLE",    qsTr("Tagpower"),   -20,    0],
                    ["CO_DANIAL",   "CO_KOAL",      qsTr("Tagpower"),   -20,    0],
                    ["CO_DANIAL",   "CO_LIN",       qsTr("Tagpower"),   -5,     0],
                    ["CO_DANIAL",   "CO_MARY",      qsTr("Tagpower"),   -10,    0],
                    ["CO_DANIAL",   "CO_MEIYO",     qsTr("Tagpower"),   -10,    0],
                    ["CO_DANIAL",   "CO_MELANTHE",  qsTr("Tagpower"),   -10,    0],
                    ["CO_DANIAL",   "CO_MINA",      qsTr("Tagpower"),   -10,    0],
                    ["CO_DANIAL",   "CO_MINAMOTO",  qsTr("Tagpower"),   -10,    0],
                    ["CO_DANIAL",   "CO_RATTIGAN",  qsTr("Tagpower"),   -10,    0],
                    ["CO_DANIAL",   "CO_SABAKI",    qsTr("Freedom Fighters"),   20,     2],
                    ["CO_DANIAL",   "CO_SMITAN",    qsTr("Tagpower"),   -20,    0],
                    ["CO_DANIAL",   "CO_SAMI",      qsTr("Tagpower"),   5,      0],
                    ["CO_DANIAL",   "CO_STURM",     qsTr("Tagpower"),   -30,    0],
                    ["CO_DANIAL",   "CO_TABITHA",   qsTr("Tagpower"),   -30,    0],
                    ["CO_DANIAL",   "CO_TASHA",     qsTr("Tagpower"),   -10,    0],
                    ["CO_DANIAL",   "CO_VON_BOLT",  qsTr("Tagpower"),   -30,    0],
                    ["CO_DANIAL",   "CO_WAYLON",    qsTr("Tagpower"),   -20,    0],
                    ["CO_DANIAL",   "CO_WILL",      qsTr("Tagpower"),   10,     1],
                    ["CO_DANIAL",   "CO_XAVIER",    qsTr("Tagpower"),   -10,    0],
                    ["CO_DANIAL",   "CO_YUKIO",     qsTr("Tagpower"),   -30,    0],
                    ["CO_DANIAL",   "CO_ZANDRA",    qsTr("Tagpower"),   10,     1],

                    ["CO_KIDD",   "CO_GRIT",        qsTr("Tagpower"),   15,     1],
);